name: Test-01

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: npm install


      - name: Deploy to Server
        run: |
          ssh  -T -o StrictHostKeyChecking=no root@168.119.254.41 << 'EOF'
              cd abdullah
              cd Test
              npm install
              npm start -d
              EOF
